### ISSUE TITLE
Switching to Cabal's new project style

### ISSUE THREAD

**Issue by nzhang-zh** [MatrixAI/Haskell-Demo#10]
From [Cabal user guide](https://www.haskell.org/cabal/users-guide/nix-local-build-overview.html)

> Nix-style local builds are a new build system implementation inspired by Nix. The Nix-style local build system is commonly called “new-build” for short after the cabal new-* family of commands that control it. However, those names are only temporary until Nix-style local builds become the default. This is expected to happen soon. For those who do not wish to use the new functionality, **the classic project style will not be removed immediately, but these legacy commands will require the usage of the v1- prefix as of Cabal 3.0 and will be removed in a future release**. For a future-proof way to use these commands in a script or tutorial that anticipates the possibility of another UI paradigm being devised in the future, there are also v2- prefixed versions that will reference the same functionality until such a point as it is completely removed from Cabal.

So to use current classic project style, append `v1-` prefix to cabal commands. `cabal v1-configure`, `cabal v1-repl` `cabal v1-build` etc

Since this is being removed in the future, consider switching to new project style soon.

**Comment by CMCDragonkai** [comment]
Can you try this out with Haskell Demo and submit a PR.

**Comment by CMCDragonkai** [comment]
This is now done. All commands are `v2-*`.
